"""empty message

Revision ID: 304926f48b4c
Revises: 4c9d445b896c
Create Date: 2022-06-26 13:14:03.715174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304926f48b4c'
down_revision = '4c9d445b896c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body1', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
